name: Test
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
jobs:
  test:
    name: Go
    runs-on: ubuntu-latest
    steps:
      - name: install-go
        uses: actions/setup-go@v3
        with:
          go-version: "1.18"

      - name: checkout
        uses: actions/checkout@v3

      - name: mod-verify
        run: go mod verify

      - name: vet
        run: go vet ./...

      - name: test
        run: go test -race -covermode atomic -coverprofile=covprofile ./...

      - name: install-goveralls
        run: go install github.com/mattn/goveralls@latest

      - name: run-goveralls
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goveralls -coverprofile=covprofile -service=github
